# Generated by Django 3.2.4 on 2022-02-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='answer',
            new_name='answers',
        ),
    ]
